Prefix: '§8[§6寵物系統§8] » '
DefaultName: §9 %player% 的寵物
OverrideDefaultName: true
EnableClickBackToMenu: true
UseDefaultMythicMobsNames: false
RightClickToOpenMenu: true
LeftClickToOpenMenu: false # true
DisableInventoryWhileHoldingSignalStick: true
DismountOnDamaged: true
SpawnPetOnReconnect: true
SneakMode: true # false
Nameable: true
Mountable: true
DistanceTeleport: 30
MaxNameLenght: 16
InventorySize: -1
PercentHealthOnRespawn: 0.2
ActivateBackMenuIcon: true
AutoSaveDelay: 3600
GlobalRespawnCooldown: false
DefaultRespawnCooldown: 0
AutoRespawn: false
Experience:
  BarSize: 40
  Symbol: '|'
  ColorDone: §a
  ColorLeft: §f
Taming:
  AnnouncementType: CHAT
  BarSize: 40
  Symbol: '|'
  ColorDone: §a
  ColorLeft: §f
DisableMySQL: true
MySQL:
  Prefix: ''
  User: user
  Password: password
  Host: localhost
  Port: '2560'
  Database: mcpets_db
BlackListedWorlds: []
